
skillMetadata:
  sections:
    - name: MyEpisodes.com Credentials
      fields:
        - name: username
          type: text
          label: Your myepisodes.com username
          value: ""
          placeholder: ""
        - name: pwhash
          type: password
          label: Your myepisodes.com MD5 hashed password
          value: ""
          placeholder: ""
    - name: Options
      fields:
        - name: useWatched
          type: checkbox
          label: Also check for unwatched shows
          value: "true"