
skillMetadata:
  sections:
    - name: MyEpisodes.com Credentials
      fields:
        - name: username
          label: Username
          type: text
          value: ""
          placeholder: ""
        - name: pwhash
          label: MD5 hashed password
          type: password
          value: ""
          placeholder: ""
    - name: Options
      fields:
        - name: useWatched
          label: Also check for unwatched shows.
          type: checkbox
          value: "true"
        - type: label
        - name: epAskCnt
          label: Maximum Episode Details
          type: number
          value: 2