
skillMetadata:
  sections:
    - name: MyEpisodes.com Credentials
      fields:
        - name: username
          label: Username
          type: text
          hint: Your myepisodes.com username
          value: ""
          placeholder: ""
        - name: pwhash
          label: MD5 hashed password
          type: password
          hint: Your myepisodes.com MD5 hashed password
          value: ""
          placeholder: ""
    - name: Options
      fields:
        - name: useWatched
          label: Get Unwatched
          type: checkbox
          hint: Also check for unwatched shows
          value: "true"
        - name: epAskCnt
          label: Ask Episode Count
          type: number
          value: 2
          hint: Ask for details if there are more than this number of episode.